

* libspotify mo
  for each playlist: is it a folder? 
    if yes, is it pandora? 
      if yes, pandorify on.
      if no, continue.
  if pandorify still off, then create folder and call pandorify_first() which will
  just add everything and not sync.

  // this for the version that syncs
  for each playlist: is it a folder? 
    if yes, is it pandora? 
      if yes, pandorify on
      if no, continue
    if no && pandorify, then it is a real playlist. for each of these: is it synced with db?
      if yes, continue
      if no, perform playlist_sync(playlist)

* playlist_sync(playlist)
  for each track in the playlist: 

* 
Should call 

javascript:$('.thumb_up_list .show_more').trigger('click')

as a link (href="") to get the show more button to expand. 

* 
subprocess
fire up node and use phantom.js zombie.js 

*
Matt 
basta@mozilla.com

* Roles
** Matt
*** Create mongodb
    Saves a user's playlist info and songs in each playlist
    Each song should have a flag that takes 3 values: 
      - Synced: The song has been synced into the playlist
      - Not-synced: The song hasn't been synced yet
      - Unavailable: The song cannot be added because it is not
        supported by spotify. 
*** Lookup songs using spotify web api
    simple.

user: wellecks@gmail.com
pw: p3nnapps
